"""
Ollama exporter: generates a Modelfile and registers the model locally.

Creates a Modelfile with the embedded system prompt, then calls
`ollama create` to register the model for local inference.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from rich.console import Console

console = Console()


def _build_modelfile(gguf_path: Path, system_prompt: str, model_name: str) -> str:
    """Generates the content of an Ollama Modelfile."""
    return f"""FROM {gguf_path}

SYSTEM \"\"\"
{system_prompt}
\"\"\"

PARAMETER temperature 0.3
PARAMETER top_p 0.9
PARAMETER num_ctx 2048

# Model: {model_name}
# Generated by fine-tune-forge
"""


def export_ollama(
    gguf_path: Path,
    model_name: str,
    system_prompt: str,
    output_dir: Path,
) -> Path:
    """
    Creates a Modelfile and registers the model with Ollama.

    Args:
        gguf_path: path to the .gguf file
        model_name: name for the Ollama model (e.g. 'agente-ristorante')
        system_prompt: system prompt to embed in the Modelfile
        output_dir: where to save the Modelfile

    Returns:
        Path to the generated Modelfile

    Raises:
        RuntimeError: if ollama create fails
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    modelfile_path = output_dir / "Modelfile"

    modelfile_content = _build_modelfile(
        gguf_path=gguf_path.resolve(),
        system_prompt=system_prompt,
        model_name=model_name,
    )

    with open(modelfile_path, "w", encoding="utf-8") as f:
        f.write(modelfile_content)

    console.print(f"Modelfile written: {modelfile_path}")
    console.print(f"Running: ollama create {model_name} -f {modelfile_path}")

    result = subprocess.run(
        ["ollama", "create", model_name, "-f", str(modelfile_path)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        console.print(f"[red]ollama create failed:[/red]\n{result.stderr}")
        raise RuntimeError(f"ollama create failed: {result.stderr}")

    console.print(f"[bold green]Ollama model registered: {model_name}[/bold green]")
    console.print(f"Test with: ollama run {model_name}")
    return modelfile_path
